DROP TABLE IF EXISTS wordlist;
CREATE TABLE IF NOT EXISTS wordlist (_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL , cid INTEGER NOT NULL , word TEXT NOT NULL );
INSERT INTO wordlist VALUES(null, 1, 'Adhesive tape');
INSERT INTO wordlist VALUES(null, 1, 'Air bags');
INSERT INTO wordlist VALUES(null, 1, 'Air conditioning');
INSERT INTO wordlist VALUES(null, 1, 'Airplane');
INSERT INTO wordlist VALUES(null, 1, 'Alternating current');
INSERT INTO wordlist VALUES(null, 1, 'Answering machine');
INSERT INTO wordlist VALUES(null, 1, 'Artificial heart');
INSERT INTO wordlist VALUES(null, 1, 'Assembly line');
INSERT INTO wordlist VALUES(null, 1, 'Atom bomb');
INSERT INTO wordlist VALUES(null, 1, 'Atomic bomb');
INSERT INTO wordlist VALUES(null, 1, 'Ball point pen');
INSERT INTO wordlist VALUES(null, 1, 'Ballistic missiles');
INSERT INTO wordlist VALUES(null, 1, 'Band-aid');
INSERT INTO wordlist VALUES(null, 1, 'Barbed wire');
INSERT INTO wordlist VALUES(null, 1, 'Barometer');
INSERT INTO wordlist VALUES(null, 1, 'Baseball');
INSERT INTO wordlist VALUES(null, 1, 'Basic');
INSERT INTO wordlist VALUES(null, 1, 'Battery');
INSERT INTO wordlist VALUES(null, 1, 'Beer');
INSERT INTO wordlist VALUES(null, 1, 'Beer cozy');
INSERT INTO wordlist VALUES(null, 1, 'Bicycle');
INSERT INTO wordlist VALUES(null, 1, 'Blackberry');
INSERT INTO wordlist VALUES(null, 1, 'Blender');
INSERT INTO wordlist VALUES(null, 1, 'Bowflex');
INSERT INTO wordlist VALUES(null, 1, 'Bra');
INSERT INTO wordlist VALUES(null, 1, 'Braille');
INSERT INTO wordlist VALUES(null, 1, 'Car');
INSERT INTO wordlist VALUES(null, 1, 'Carmex');
INSERT INTO wordlist VALUES(null, 1, 'Cash register');
INSERT INTO wordlist VALUES(null, 1, 'Cat-scans');
INSERT INTO wordlist VALUES(null, 1, 'Catheter');
INSERT INTO wordlist VALUES(null, 1, 'Cellophane');
INSERT INTO wordlist VALUES(null, 1, 'Cellular phone');
INSERT INTO wordlist VALUES(null, 1, 'Clapper');
INSERT INTO wordlist VALUES(null, 1, 'Cloning');
INSERT INTO wordlist VALUES(null, 1, 'Closed captioning');
INSERT INTO wordlist VALUES(null, 1, 'Coca cola');
INSERT INTO wordlist VALUES(null, 1, 'Cold fusion energy');
INSERT INTO wordlist VALUES(null, 1, 'Colt revolver');
INSERT INTO wordlist VALUES(null, 1, 'Computer');
INSERT INTO wordlist VALUES(null, 1, 'Cordite');
INSERT INTO wordlist VALUES(null, 1, 'Cotton gin');
INSERT INTO wordlist VALUES(null, 1, 'Deodorant');
INSERT INTO wordlist VALUES(null, 1, 'Dialysis machine');
INSERT INTO wordlist VALUES(null, 1, 'Dildo');
INSERT INTO wordlist VALUES(null, 1, 'Earmuff');
INSERT INTO wordlist VALUES(null, 1, 'Eggs');
INSERT INTO wordlist VALUES(null, 1, 'Electric blanket');
INSERT INTO wordlist VALUES(null, 1, 'Electricity ');
INSERT INTO wordlist VALUES(null, 1, 'Electromagnet');
INSERT INTO wordlist VALUES(null, 1, 'Elevator');
INSERT INTO wordlist VALUES(null, 1, 'Erector set');
INSERT INTO wordlist VALUES(null, 1, 'Escalator');
INSERT INTO wordlist VALUES(null, 1, 'Ethernet');
INSERT INTO wordlist VALUES(null, 1, 'Feet');
INSERT INTO wordlist VALUES(null, 1, 'Fiber optics');
INSERT INTO wordlist VALUES(null, 1, 'Flying car');
INSERT INTO wordlist VALUES(null, 1, 'Fortran');
INSERT INTO wordlist VALUES(null, 1, 'Freon');
INSERT INTO wordlist VALUES(null, 1, 'Global positioning system');
INSERT INTO wordlist VALUES(null, 1, 'Graham cracker');
INSERT INTO wordlist VALUES(null, 1, 'Gramophone');
INSERT INTO wordlist VALUES(null, 1, 'Grocery bag');
INSERT INTO wordlist VALUES(null, 1, 'Guitar');
INSERT INTO wordlist VALUES(null, 1, 'Gum');
INSERT INTO wordlist VALUES(null, 1, 'Hacky sack');
INSERT INTO wordlist VALUES(null, 1, 'Hanger');
INSERT INTO wordlist VALUES(null, 1, 'Hat');
INSERT INTO wordlist VALUES(null, 1, 'Hats');
INSERT INTO wordlist VALUES(null, 1, 'Hill top hoist');
INSERT INTO wordlist VALUES(null, 1, 'Hyperbaric oxygen chamber');
INSERT INTO wordlist VALUES(null, 1, 'Jesus');
INSERT INTO wordlist VALUES(null, 1, 'Large hadron collider');
INSERT INTO wordlist VALUES(null, 1, 'Liposuction');
INSERT INTO wordlist VALUES(null, 1, 'Megaphone');
INSERT INTO wordlist VALUES(null, 1, 'Microwave');
INSERT INTO wordlist VALUES(null, 1, 'Paper clip');
INSERT INTO wordlist VALUES(null, 1, 'Pet rock');
INSERT INTO wordlist VALUES(null, 1, 'Phone');
INSERT INTO wordlist VALUES(null, 1, 'Printing press');
INSERT INTO wordlist VALUES(null, 1, 'Prosthetics');
INSERT INTO wordlist VALUES(null, 1, 'Qwerty');
INSERT INTO wordlist VALUES(null, 1, 'Rollerblades');
INSERT INTO wordlist VALUES(null, 1, 'Saxophone');
INSERT INTO wordlist VALUES(null, 1, 'Sonar');
INSERT INTO wordlist VALUES(null, 1, 'Steam engine');
INSERT INTO wordlist VALUES(null, 1, 'Still');
INSERT INTO wordlist VALUES(null, 1, 'Styrofoam');
INSERT INTO wordlist VALUES(null, 1, 'Sun dial');
INSERT INTO wordlist VALUES(null, 1, 'Telephone');
INSERT INTO wordlist VALUES(null, 1, 'Vaccines');
INSERT INTO wordlist VALUES(null, 1, 'Velcro');
INSERT INTO wordlist VALUES(null, 1, 'Wheel');
INSERT INTO wordlist VALUES(null, 1, 'Www');
INSERT INTO wordlist VALUES(null, 1, 'Xerox');
INSERT INTO wordlist VALUES(null, 2, '12/7/1942');
INSERT INTO wordlist VALUES(null, 2, '1492');
INSERT INTO wordlist VALUES(null, 2, '1916 rising');
INSERT INTO wordlist VALUES(null, 2, '9-11-01');
INSERT INTO wordlist VALUES(null, 2, 'Age of enlightenment');
INSERT INTO wordlist VALUES(null, 2, 'Alamo');
INSERT INTO wordlist VALUES(null, 2, 'American revolution');
INSERT INTO wordlist VALUES(null, 2, 'Andy warhol');
INSERT INTO wordlist VALUES(null, 2, 'Anne frank');
INSERT INTO wordlist VALUES(null, 2, 'Annie oakley');
INSERT INTO wordlist VALUES(null, 2, 'Anthrax');
INSERT INTO wordlist VALUES(null, 2, 'Axis/ allies');
INSERT INTO wordlist VALUES(null, 2, 'Baghdad');
INSERT INTO wordlist VALUES(null, 2, 'Barack obama');
INSERT INTO wordlist VALUES(null, 2, 'Battle of midway');
INSERT INTO wordlist VALUES(null, 2, 'Battle of the Bulge');
INSERT INTO wordlist VALUES(null, 2, 'Billie holiday');
INSERT INTO wordlist VALUES(null, 2, 'Bloody sunday');
INSERT INTO wordlist VALUES(null, 2, 'Bonnie and clyde');
INSERT INTO wordlist VALUES(null, 2, 'Bootlegging');
INSERT INTO wordlist VALUES(null, 2, 'Boston tea party');
INSERT INTO wordlist VALUES(null, 2, 'Bronze age');
INSERT INTO wordlist VALUES(null, 2, 'Byzantine empire');
INSERT INTO wordlist VALUES(null, 2, 'Christopher columbus');
INSERT INTO wordlist VALUES(null, 2, 'Civil war');
INSERT INTO wordlist VALUES(null, 2, 'Coco chanel');
INSERT INTO wordlist VALUES(null, 2, 'Cold war');
INSERT INTO wordlist VALUES(null, 2, 'Columbine massacre');
INSERT INTO wordlist VALUES(null, 2, 'Confederate');
INSERT INTO wordlist VALUES(null, 2, 'Constitution');
INSERT INTO wordlist VALUES(null, 2, 'Daniel boone');
INSERT INTO wordlist VALUES(null, 2, 'Dark ages');
INSERT INTO wordlist VALUES(null, 2, 'Dead sea scrolls');
INSERT INTO wordlist VALUES(null, 2, 'Declaration of indepedence');
INSERT INTO wordlist VALUES(null, 2, 'Digital age');
INSERT INTO wordlist VALUES(null, 2, 'Empire of eldorado ');
INSERT INTO wordlist VALUES(null, 2, 'Enrico fermi');
INSERT INTO wordlist VALUES(null, 2, 'Ferdinand magellan');
INSERT INTO wordlist VALUES(null, 2, 'General valeriano weyler');
INSERT INTO wordlist VALUES(null, 2, 'George washington');
INSERT INTO wordlist VALUES(null, 2, 'Gold rush');
INSERT INTO wordlist VALUES(null, 2, 'Great depression');
INSERT INTO wordlist VALUES(null, 2, 'Guadalcanal campaign');
INSERT INTO wordlist VALUES(null, 2, 'Harriet tubman');
INSERT INTO wordlist VALUES(null, 2, 'Hitler');
INSERT INTO wordlist VALUES(null, 2, 'Holocaust');
INSERT INTO wordlist VALUES(null, 2, 'House of gediminas');
INSERT INTO wordlist VALUES(null, 2, 'Howard hughes');
INSERT INTO wordlist VALUES(null, 2, 'Industrial revolution');
INSERT INTO wordlist VALUES(null, 2, 'Joan of arc');
INSERT INTO wordlist VALUES(null, 2, 'John quincy adams');
INSERT INTO wordlist VALUES(null, 2, 'Laika the dog');
INSERT INTO wordlist VALUES(null, 2, 'Laylat al-qadr');
INSERT INTO wordlist VALUES(null, 2, 'League of nations');
INSERT INTO wordlist VALUES(null, 2, 'Leonard wood');
INSERT INTO wordlist VALUES(null, 2, 'Lewis & clark');
INSERT INTO wordlist VALUES(null, 2, 'Louis and clark');
INSERT INTO wordlist VALUES(null, 2, 'Machu picchu');
INSERT INTO wordlist VALUES(null, 2, 'Mahatma gandhi');
INSERT INTO wordlist VALUES(null, 2, 'Malcomm x');
INSERT INTO wordlist VALUES(null, 2, 'Martin luther king, jr.');
INSERT INTO wordlist VALUES(null, 2, 'Mary queen of scots');
INSERT INTO wordlist VALUES(null, 2, 'Michelangelo');
INSERT INTO wordlist VALUES(null, 2, 'Ming dynasty');
INSERT INTO wordlist VALUES(null, 2, 'Monica lewinsky');
INSERT INTO wordlist VALUES(null, 2, 'Monroe doctrine');
INSERT INTO wordlist VALUES(null, 2, 'Mt. saint helens');
INSERT INTO wordlist VALUES(null, 2, 'Native american');
INSERT INTO wordlist VALUES(null, 2, 'Ok corral');
INSERT INTO wordlist VALUES(null, 2, 'Oregon trail');
INSERT INTO wordlist VALUES(null, 2, 'Pearl harbor');
INSERT INTO wordlist VALUES(null, 2, 'Princess diana');
INSERT INTO wordlist VALUES(null, 2, 'Prohibition');
INSERT INTO wordlist VALUES(null, 2, 'Railroad');
INSERT INTO wordlist VALUES(null, 2, 'Renaissance');
INSERT INTO wordlist VALUES(null, 2, 'Rough riders');
INSERT INTO wordlist VALUES(null, 2, 'Saber toothed tiger');
INSERT INTO wordlist VALUES(null, 2, 'Shakespeare');
INSERT INTO wordlist VALUES(null, 2, 'Sierra sam');
INSERT INTO wordlist VALUES(null, 2, 'Spanish armada');
INSERT INTO wordlist VALUES(null, 2, 'Spanish-american war');
INSERT INTO wordlist VALUES(null, 2, 'Star of india');
INSERT INTO wordlist VALUES(null, 2, 'Statue of liberty');
INSERT INTO wordlist VALUES(null, 2, 'Stem cell research');
INSERT INTO wordlist VALUES(null, 2, 'The alamo');
INSERT INTO wordlist VALUES(null, 2, 'The spitsbergen treaty');
INSERT INTO wordlist VALUES(null, 2, 'Theodore roosevelt');
INSERT INTO wordlist VALUES(null, 2, 'Tomb of king tut');
INSERT INTO wordlist VALUES(null, 2, 'Treaty of paris');
INSERT INTO wordlist VALUES(null, 2, 'United states of america');
INSERT INTO wordlist VALUES(null, 2, 'Usa');
INSERT INTO wordlist VALUES(null, 2, 'Ussr');
INSERT INTO wordlist VALUES(null, 2, 'Waco');
INSERT INTO wordlist VALUES(null, 2, 'Walkie talkie');
INSERT INTO wordlist VALUES(null, 2, 'William randolph hearst');
INSERT INTO wordlist VALUES(null, 2, 'Winston churchill');
INSERT INTO wordlist VALUES(null, 2, 'World war 1');
INSERT INTO wordlist VALUES(null, 2, 'World war 2');
INSERT INTO wordlist VALUES(null, 3, 'Action');
INSERT INTO wordlist VALUES(null, 3, 'Adult film');
INSERT INTO wordlist VALUES(null, 3, 'American history x');
INSERT INTO wordlist VALUES(null, 3, 'Amy smart');
INSERT INTO wordlist VALUES(null, 3, 'Applause');
INSERT INTO wordlist VALUES(null, 3, 'Ashton kutcher');
INSERT INTO wordlist VALUES(null, 3, 'Backgammon');
INSERT INTO wordlist VALUES(null, 3, 'Bar hopping');
INSERT INTO wordlist VALUES(null, 3, 'Bars');
INSERT INTO wordlist VALUES(null, 3, 'Blu ray');
INSERT INTO wordlist VALUES(null, 3, 'Bozo the clown');
INSERT INTO wordlist VALUES(null, 3, 'Broadway');
INSERT INTO wordlist VALUES(null, 3, 'Bruce willis');
INSERT INTO wordlist VALUES(null, 3, 'Catch phrase');
INSERT INTO wordlist VALUES(null, 3, 'Chinese checkers');
INSERT INTO wordlist VALUES(null, 3, 'Circus');
INSERT INTO wordlist VALUES(null, 3, 'Clown');
INSERT INTO wordlist VALUES(null, 3, 'Comedy');
INSERT INTO wordlist VALUES(null, 3, 'Concert');
INSERT INTO wordlist VALUES(null, 3, 'Connect-four');
INSERT INTO wordlist VALUES(null, 3, 'Dance');
INSERT INTO wordlist VALUES(null, 3, 'Dave chappelle');
INSERT INTO wordlist VALUES(null, 3, 'Demi moore');
INSERT INTO wordlist VALUES(null, 3, 'Digeridoo');
INSERT INTO wordlist VALUES(null, 3, 'Digg.com');
INSERT INTO wordlist VALUES(null, 3, 'Dominoes');
INSERT INTO wordlist VALUES(null, 3, 'Drama');
INSERT INTO wordlist VALUES(null, 3, 'Drum');
INSERT INTO wordlist VALUES(null, 3, 'Etch-a-sketch');
INSERT INTO wordlist VALUES(null, 3, 'Facebook');
INSERT INTO wordlist VALUES(null, 3, 'Fire walking');
INSERT INTO wordlist VALUES(null, 3, 'Flute');
INSERT INTO wordlist VALUES(null, 3, 'Food');
INSERT INTO wordlist VALUES(null, 3, 'Frisbee');
INSERT INTO wordlist VALUES(null, 3, 'Game');
INSERT INTO wordlist VALUES(null, 3, 'Gameboy');
INSERT INTO wordlist VALUES(null, 3, 'Glow sticks');
INSERT INTO wordlist VALUES(null, 3, 'Guitar hero world tour');
INSERT INTO wordlist VALUES(null, 3, 'Hackey sack');
INSERT INTO wordlist VALUES(null, 3, 'Horror');
INSERT INTO wordlist VALUES(null, 3, 'Hugh jackman');
INSERT INTO wordlist VALUES(null, 3, 'Intercourse');
INSERT INTO wordlist VALUES(null, 3, 'Ipod');
INSERT INTO wordlist VALUES(null, 3, 'Jay leno');
INSERT INTO wordlist VALUES(null, 3, 'Jennifer aniston');
INSERT INTO wordlist VALUES(null, 3, 'Jet ski');
INSERT INTO wordlist VALUES(null, 3, 'Jig-saw puzzle');
INSERT INTO wordlist VALUES(null, 3, 'Jinga');
INSERT INTO wordlist VALUES(null, 3, 'Jukebox');
INSERT INTO wordlist VALUES(null, 3, 'Kaleidoscope');
INSERT INTO wordlist VALUES(null, 3, 'Knife throwing');
INSERT INTO wordlist VALUES(null, 3, 'Magic mountain');
INSERT INTO wordlist VALUES(null, 3, 'Magic tricks');
INSERT INTO wordlist VALUES(null, 3, 'Monopoly');
INSERT INTO wordlist VALUES(null, 3, 'Movie');
INSERT INTO wordlist VALUES(null, 3, 'Movies');
INSERT INTO wordlist VALUES(null, 3, 'Mr potato head');
INSERT INTO wordlist VALUES(null, 3, 'Music');
INSERT INTO wordlist VALUES(null, 3, 'Myspace');
INSERT INTO wordlist VALUES(null, 3, 'Nine inch nails');
INSERT INTO wordlist VALUES(null, 3, 'Nintendo');
INSERT INTO wordlist VALUES(null, 3, 'Nirvana');
INSERT INTO wordlist VALUES(null, 3, 'Organ');
INSERT INTO wordlist VALUES(null, 3, 'Piano');
INSERT INTO wordlist VALUES(null, 3, 'Play');
INSERT INTO wordlist VALUES(null, 3, 'Play-doh');
INSERT INTO wordlist VALUES(null, 3, 'Playstation');
INSERT INTO wordlist VALUES(null, 3, 'Pogo-stick');
INSERT INTO wordlist VALUES(null, 3, 'Poker');
INSERT INTO wordlist VALUES(null, 3, 'Puddle jumping');
INSERT INTO wordlist VALUES(null, 3, 'Puppet show');
INSERT INTO wordlist VALUES(null, 3, 'Red hot chili peppers');
INSERT INTO wordlist VALUES(null, 3, 'Restaurants');
INSERT INTO wordlist VALUES(null, 3, 'Rollercoaster');
INSERT INTO wordlist VALUES(null, 3, 'Rubiks cube');
INSERT INTO wordlist VALUES(null, 3, 'Shows');
INSERT INTO wordlist VALUES(null, 3, 'Silly putty');
INSERT INTO wordlist VALUES(null, 3, 'Slinky');
INSERT INTO wordlist VALUES(null, 3, 'Slot machine');
INSERT INTO wordlist VALUES(null, 3, 'Spinning top');
INSERT INTO wordlist VALUES(null, 3, 'Starcraft');
INSERT INTO wordlist VALUES(null, 3, 'Super soaker');
INSERT INTO wordlist VALUES(null, 3, 'Suspense');
INSERT INTO wordlist VALUES(null, 3, 'Sword swallowing');
INSERT INTO wordlist VALUES(null, 3, 'Texas holdem');
INSERT INTO wordlist VALUES(null, 3, 'Theater');
INSERT INTO wordlist VALUES(null, 3, 'Theatre');
INSERT INTO wordlist VALUES(null, 3, 'Thriller');
INSERT INTO wordlist VALUES(null, 3, 'Trampoline');
INSERT INTO wordlist VALUES(null, 3, 'Trivial pursuit');
INSERT INTO wordlist VALUES(null, 3, 'Video game');
INSERT INTO wordlist VALUES(null, 3, 'Vince vaughn');
INSERT INTO wordlist VALUES(null, 3, 'Wax museum');
INSERT INTO wordlist VALUES(null, 3, 'Yo-yo');
INSERT INTO wordlist VALUES(null, 3, 'Youtube');
INSERT INTO wordlist VALUES(null, 4, 'Aikido');
INSERT INTO wordlist VALUES(null, 4, 'Airsoft');
INSERT INTO wordlist VALUES(null, 4, 'Allstar');
INSERT INTO wordlist VALUES(null, 4, 'Alpine skiing');
INSERT INTO wordlist VALUES(null, 4, 'Arena');
INSERT INTO wordlist VALUES(null, 4, 'Arm wrestling');
INSERT INTO wordlist VALUES(null, 4, 'Badminton');
INSERT INTO wordlist VALUES(null, 4, 'Ball park');
INSERT INTO wordlist VALUES(null, 4, 'Ballet');
INSERT INTO wordlist VALUES(null, 4, 'Band');
INSERT INTO wordlist VALUES(null, 4, 'Base jumping');
INSERT INTO wordlist VALUES(null, 4, 'Basktball');
INSERT INTO wordlist VALUES(null, 4, 'Bass fishing');
INSERT INTO wordlist VALUES(null, 4, 'Beer pong');
INSERT INTO wordlist VALUES(null, 4, 'Bike');
INSERT INTO wordlist VALUES(null, 4, 'Blackberry thumb');
INSERT INTO wordlist VALUES(null, 4, 'Bmx ');
INSERT INTO wordlist VALUES(null, 4, 'Bob sleigh');
INSERT INTO wordlist VALUES(null, 4, 'Bocchi ball');
INSERT INTO wordlist VALUES(null, 4, 'Boomerang');
INSERT INTO wordlist VALUES(null, 4, 'Bouldering');
INSERT INTO wordlist VALUES(null, 4, 'Bowling');
INSERT INTO wordlist VALUES(null, 4, 'Boxing');
INSERT INTO wordlist VALUES(null, 4, 'Broomball');
INSERT INTO wordlist VALUES(null, 4, 'Buns of steel');
INSERT INTO wordlist VALUES(null, 4, 'Center');
INSERT INTO wordlist VALUES(null, 4, 'Checkers');
INSERT INTO wordlist VALUES(null, 4, 'Cheer');
INSERT INTO wordlist VALUES(null, 4, 'Cheerleader');
INSERT INTO wordlist VALUES(null, 4, 'Chess');
INSERT INTO wordlist VALUES(null, 4, 'Court');
INSERT INTO wordlist VALUES(null, 4, 'Cribbage');
INSERT INTO wordlist VALUES(null, 4, 'Cricket');
INSERT INTO wordlist VALUES(null, 4, 'Croquet');
INSERT INTO wordlist VALUES(null, 4, 'Curling');
INSERT INTO wordlist VALUES(null, 4, 'Defense');
INSERT INTO wordlist VALUES(null, 4, 'Deflection');
INSERT INTO wordlist VALUES(null, 4, 'Dirt bike');
INSERT INTO wordlist VALUES(null, 4, 'Dodgeball');
INSERT INTO wordlist VALUES(null, 4, 'Drag racing');
INSERT INTO wordlist VALUES(null, 4, 'Duck hunting');
INSERT INTO wordlist VALUES(null, 4, 'Endorsement');
INSERT INTO wordlist VALUES(null, 4, 'Endurance');
INSERT INTO wordlist VALUES(null, 4, 'Fencing ');
INSERT INTO wordlist VALUES(null, 4, 'Field');
INSERT INTO wordlist VALUES(null, 4, 'Fieldgoal');
INSERT INTO wordlist VALUES(null, 4, 'First base');
INSERT INTO wordlist VALUES(null, 4, 'Fly fishing');
INSERT INTO wordlist VALUES(null, 4, 'Foosball');
INSERT INTO wordlist VALUES(null, 4, 'Football');
INSERT INTO wordlist VALUES(null, 4, 'Forward');
INSERT INTO wordlist VALUES(null, 4, 'Foul');
INSERT INTO wordlist VALUES(null, 4, 'Four square');
INSERT INTO wordlist VALUES(null, 4, 'Free throw');
INSERT INTO wordlist VALUES(null, 4, 'Freestyle');
INSERT INTO wordlist VALUES(null, 4, 'Frisbee golf');
INSERT INTO wordlist VALUES(null, 4, 'Gatorade');
INSERT INTO wordlist VALUES(null, 4, 'Gloves');
INSERT INTO wordlist VALUES(null, 4, 'Goal');
INSERT INTO wordlist VALUES(null, 4, 'Golf');
INSERT INTO wordlist VALUES(null, 4, 'Golf tee');
INSERT INTO wordlist VALUES(null, 4, 'Grand prix');
INSERT INTO wordlist VALUES(null, 4, 'Guard');
INSERT INTO wordlist VALUES(null, 4, 'Hail mary');
INSERT INTO wordlist VALUES(null, 4, 'Half-pipe');
INSERT INTO wordlist VALUES(null, 4, 'Handball');
INSERT INTO wordlist VALUES(null, 4, 'Hang gliding');
INSERT INTO wordlist VALUES(null, 4, 'Helmet');
INSERT INTO wordlist VALUES(null, 4, 'Helmets');
INSERT INTO wordlist VALUES(null, 4, 'Hide and seek');
INSERT INTO wordlist VALUES(null, 4, 'High dive');
INSERT INTO wordlist VALUES(null, 4, 'Hockey');
INSERT INTO wordlist VALUES(null, 4, 'Hockey puck');
INSERT INTO wordlist VALUES(null, 4, 'Home plate');
INSERT INTO wordlist VALUES(null, 4, 'Hoop');
INSERT INTO wordlist VALUES(null, 4, 'Hopscotch');
INSERT INTO wordlist VALUES(null, 4, 'Horse shoes');
INSERT INTO wordlist VALUES(null, 4, 'Hurdle');
INSERT INTO wordlist VALUES(null, 4, 'Hurdles');
INSERT INTO wordlist VALUES(null, 4, 'Ice hockey');
INSERT INTO wordlist VALUES(null, 4, 'Injuries');
INSERT INTO wordlist VALUES(null, 4, 'Inning');
INSERT INTO wordlist VALUES(null, 4, 'Javelin');
INSERT INTO wordlist VALUES(null, 4, 'Jiu-jitsu');
INSERT INTO wordlist VALUES(null, 4, 'Jock strap');
INSERT INTO wordlist VALUES(null, 4, 'Kabaddi');
INSERT INTO wordlist VALUES(null, 4, 'Kayaking');
INSERT INTO wordlist VALUES(null, 4, 'Kite flying');
INSERT INTO wordlist VALUES(null, 4, 'Kite surfing');
INSERT INTO wordlist VALUES(null, 4, 'Lacross');
INSERT INTO wordlist VALUES(null, 4, 'Lacrosse');
INSERT INTO wordlist VALUES(null, 4, 'Lasar tag');
INSERT INTO wordlist VALUES(null, 4, 'Loss');
INSERT INTO wordlist VALUES(null, 4, 'Marathon');
INSERT INTO wordlist VALUES(null, 4, 'Mascot');
INSERT INTO wordlist VALUES(null, 4, 'Miniature golf');
INSERT INTO wordlist VALUES(null, 4, 'Monster truck');
INSERT INTO wordlist VALUES(null, 4, 'Motorcross');
INSERT INTO wordlist VALUES(null, 4, 'Mountain biking');
INSERT INTO wordlist VALUES(null, 4, 'Mulligan');
INSERT INTO wordlist VALUES(null, 4, 'Muscles');
INSERT INTO wordlist VALUES(null, 4, 'Net');
INSERT INTO wordlist VALUES(null, 4, 'Nfl');
INSERT INTO wordlist VALUES(null, 4, 'Nhl');
INSERT INTO wordlist VALUES(null, 4, 'Nine iron');
INSERT INTO wordlist VALUES(null, 4, 'Nine-ball');
INSERT INTO wordlist VALUES(null, 4, 'Off roading');
INSERT INTO wordlist VALUES(null, 4, 'Offense');
INSERT INTO wordlist VALUES(null, 4, 'Olympics');
INSERT INTO wordlist VALUES(null, 4, 'Overtime');
INSERT INTO wordlist VALUES(null, 4, 'Paddle ball');
INSERT INTO wordlist VALUES(null, 4, 'Paddle boat');
INSERT INTO wordlist VALUES(null, 4, 'Paintball');
INSERT INTO wordlist VALUES(null, 4, 'Pass');
INSERT INTO wordlist VALUES(null, 4, 'Penalty');
INSERT INTO wordlist VALUES(null, 4, 'Pitcher');
INSERT INTO wordlist VALUES(null, 4, 'Polio');
INSERT INTO wordlist VALUES(null, 4, 'Polo');
INSERT INTO wordlist VALUES(null, 4, 'Pom poms');
INSERT INTO wordlist VALUES(null, 4, 'Pop fly');
INSERT INTO wordlist VALUES(null, 4, 'Power forward');
INSERT INTO wordlist VALUES(null, 4, 'Racing');
INSERT INTO wordlist VALUES(null, 4, 'Raquet');
INSERT INTO wordlist VALUES(null, 4, 'Red rover');
INSERT INTO wordlist VALUES(null, 4, 'Roller skates');
INSERT INTO wordlist VALUES(null, 4, 'Rugby');
INSERT INTO wordlist VALUES(null, 4, 'Score');
INSERT INTO wordlist VALUES(null, 4, 'Screen pass');
INSERT INTO wordlist VALUES(null, 4, 'Second base');
INSERT INTO wordlist VALUES(null, 4, 'Shooting range');
INSERT INTO wordlist VALUES(null, 4, 'Shuffle board');
INSERT INTO wordlist VALUES(null, 4, 'Skateboard');
INSERT INTO wordlist VALUES(null, 4, 'Skates');
INSERT INTO wordlist VALUES(null, 4, 'Ski');
INSERT INTO wordlist VALUES(null, 4, 'Sky diving');
INSERT INTO wordlist VALUES(null, 4, 'Skydiving');
INSERT INTO wordlist VALUES(null, 4, 'Slacklining');
INSERT INTO wordlist VALUES(null, 4, 'Slosh ball');
INSERT INTO wordlist VALUES(null, 4, 'Snorkeling');
INSERT INTO wordlist VALUES(null, 4, 'Snow sled');
INSERT INTO wordlist VALUES(null, 4, 'Snowboard');
INSERT INTO wordlist VALUES(null, 4, 'Soccer');
INSERT INTO wordlist VALUES(null, 4, 'Speed');
INSERT INTO wordlist VALUES(null, 4, 'Speed walking');
INSERT INTO wordlist VALUES(null, 4, 'Sprinting');
INSERT INTO wordlist VALUES(null, 4, 'Stadium');
INSERT INTO wordlist VALUES(null, 4, 'Sumo wrestling');
INSERT INTO wordlist VALUES(null, 4, 'Swimming');
INSERT INTO wordlist VALUES(null, 4, 'Table tennis');
INSERT INTO wordlist VALUES(null, 4, 'Taekwondo');
INSERT INTO wordlist VALUES(null, 4, 'Tai chi chuan');
INSERT INTO wordlist VALUES(null, 4, 'Team');
INSERT INTO wordlist VALUES(null, 4, 'Tennis');
INSERT INTO wordlist VALUES(null, 4, 'Tennis elbow');
INSERT INTO wordlist VALUES(null, 4, 'Third base');
INSERT INTO wordlist VALUES(null, 4, 'Three-legged race');
INSERT INTO wordlist VALUES(null, 4, 'Thumb war');
INSERT INTO wordlist VALUES(null, 4, 'Tie');
INSERT INTO wordlist VALUES(null, 4, 'Tightrope ');
INSERT INTO wordlist VALUES(null, 4, 'Touchdown');
INSERT INTO wordlist VALUES(null, 4, 'Trapezee');
INSERT INTO wordlist VALUES(null, 4, 'Triathlon');
INSERT INTO wordlist VALUES(null, 4, 'Tug of war');
INSERT INTO wordlist VALUES(null, 4, 'Ultimate frisbee');
INSERT INTO wordlist VALUES(null, 4, 'Unicycle');
INSERT INTO wordlist VALUES(null, 4, 'Uniform');
INSERT INTO wordlist VALUES(null, 4, 'Volleyball');
INSERT INTO wordlist VALUES(null, 4, 'Water polo');
INSERT INTO wordlist VALUES(null, 4, 'White water rafting');
INSERT INTO wordlist VALUES(null, 4, 'Wide reciever');
INSERT INTO wordlist VALUES(null, 4, 'Wiffleball');
INSERT INTO wordlist VALUES(null, 4, 'Win');
INSERT INTO wordlist VALUES(null, 4, 'Wind surfing');
INSERT INTO wordlist VALUES(null, 4, 'Yards');
INSERT INTO wordlist VALUES(null, 5, 'Africa');
INSERT INTO wordlist VALUES(null, 5, 'Alaska');
INSERT INTO wordlist VALUES(null, 5, 'Amazon river');
INSERT INTO wordlist VALUES(null, 5, 'Antartica');
INSERT INTO wordlist VALUES(null, 5, 'Asia');
INSERT INTO wordlist VALUES(null, 5, 'Atlantic ocean');
INSERT INTO wordlist VALUES(null, 5, 'Australia');
INSERT INTO wordlist VALUES(null, 5, 'Bali');
INSERT INTO wordlist VALUES(null, 5, 'Bering strait');
INSERT INTO wordlist VALUES(null, 5, 'Berlin wall');
INSERT INTO wordlist VALUES(null, 5, 'Brazil');
INSERT INTO wordlist VALUES(null, 5, 'Canada');
INSERT INTO wordlist VALUES(null, 5, 'Cardinal directions');
INSERT INTO wordlist VALUES(null, 5, 'China');
INSERT INTO wordlist VALUES(null, 5, 'Compass');
INSERT INTO wordlist VALUES(null, 5, 'Continents');
INSERT INTO wordlist VALUES(null, 5, 'Countries');
INSERT INTO wordlist VALUES(null, 5, 'Degrees');
INSERT INTO wordlist VALUES(null, 5, 'Denmark');
INSERT INTO wordlist VALUES(null, 5, 'East');
INSERT INTO wordlist VALUES(null, 5, 'Egypt');
INSERT INTO wordlist VALUES(null, 5, 'Europe');
INSERT INTO wordlist VALUES(null, 5, 'Florida');
INSERT INTO wordlist VALUES(null, 5, 'Galveston, tx');
INSERT INTO wordlist VALUES(null, 5, 'Germany');
INSERT INTO wordlist VALUES(null, 5, 'Grand canyon');
INSERT INTO wordlist VALUES(null, 5, 'Great britian');
INSERT INTO wordlist VALUES(null, 5, 'Greenland');
INSERT INTO wordlist VALUES(null, 5, 'Hawaii');
INSERT INTO wordlist VALUES(null, 5, 'Hudson river');
INSERT INTO wordlist VALUES(null, 5, 'Iceland');
INSERT INTO wordlist VALUES(null, 5, 'India');
INSERT INTO wordlist VALUES(null, 5, 'Indian ocean');
INSERT INTO wordlist VALUES(null, 5, 'Italy');
INSERT INTO wordlist VALUES(null, 5, 'Japan');
INSERT INTO wordlist VALUES(null, 5, 'Lake erie');
INSERT INTO wordlist VALUES(null, 5, 'Lake michigan');
INSERT INTO wordlist VALUES(null, 5, 'Lake of the ozarks');
INSERT INTO wordlist VALUES(null, 5, 'Lake superior');
INSERT INTO wordlist VALUES(null, 5, 'Lake tahoe');
INSERT INTO wordlist VALUES(null, 5, 'Latitude');
INSERT INTO wordlist VALUES(null, 5, 'Longitude');
INSERT INTO wordlist VALUES(null, 5, 'Mammoth mountain');
INSERT INTO wordlist VALUES(null, 5, 'Maps');
INSERT INTO wordlist VALUES(null, 5, 'Mexico');
INSERT INTO wordlist VALUES(null, 5, 'Mysore, india');
INSERT INTO wordlist VALUES(null, 5, 'New orleans, la');
INSERT INTO wordlist VALUES(null, 5, 'New zeland');
INSERT INTO wordlist VALUES(null, 5, 'Niagra falls');
INSERT INTO wordlist VALUES(null, 5, 'Nile river');
INSERT INTO wordlist VALUES(null, 5, 'North');
INSERT INTO wordlist VALUES(null, 5, 'North america');
INSERT INTO wordlist VALUES(null, 5, 'Pacific ocean');
INSERT INTO wordlist VALUES(null, 5, 'Pentagon');
INSERT INTO wordlist VALUES(null, 5, 'Physical');
INSERT INTO wordlist VALUES(null, 5, 'Poland');
INSERT INTO wordlist VALUES(null, 5, 'Rocky mountains');
INSERT INTO wordlist VALUES(null, 5, 'Russia');
INSERT INTO wordlist VALUES(null, 5, 'Sahara desert');
INSERT INTO wordlist VALUES(null, 5, 'San diego');
INSERT INTO wordlist VALUES(null, 5, 'Siberia');
INSERT INTO wordlist VALUES(null, 5, 'Singapore');
INSERT INTO wordlist VALUES(null, 5, 'South');
INSERT INTO wordlist VALUES(null, 5, 'South america');
INSERT INTO wordlist VALUES(null, 5, 'Spain');
INSERT INTO wordlist VALUES(null, 5, 'Stonehenge');
INSERT INTO wordlist VALUES(null, 5, 'Sweden');
INSERT INTO wordlist VALUES(null, 5, 'Taj mahal');
INSERT INTO wordlist VALUES(null, 5, 'Texas');
INSERT INTO wordlist VALUES(null, 5, 'Thailand');
INSERT INTO wordlist VALUES(null, 5, 'The alps');
INSERT INTO wordlist VALUES(null, 5, 'The white house');
INSERT INTO wordlist VALUES(null, 5, 'Tropic of cancer');
INSERT INTO wordlist VALUES(null, 5, 'Turkey');
INSERT INTO wordlist VALUES(null, 5, 'Unimak pass');
INSERT INTO wordlist VALUES(null, 5, 'United states');
INSERT INTO wordlist VALUES(null, 5, 'West');
INSERT INTO wordlist VALUES(null, 5, 'Whistler blackcomb');
INSERT INTO wordlist VALUES(null, 5, 'World trade center');
INSERT INTO wordlist VALUES(null, 6, '24 hour fitness');
INSERT INTO wordlist VALUES(null, 6, '3 day weekend');
INSERT INTO wordlist VALUES(null, 6, 'Accountant');
INSERT INTO wordlist VALUES(null, 6, 'Add');
INSERT INTO wordlist VALUES(null, 6, 'Adding');
INSERT INTO wordlist VALUES(null, 6, 'Administration');
INSERT INTO wordlist VALUES(null, 6, 'Albertsons');
INSERT INTO wordlist VALUES(null, 6, 'Ambulance');
INSERT INTO wordlist VALUES(null, 6, 'Anarchy');
INSERT INTO wordlist VALUES(null, 6, 'Apartment');
INSERT INTO wordlist VALUES(null, 6, 'Appointments');
INSERT INTO wordlist VALUES(null, 6, 'Assume');
INSERT INTO wordlist VALUES(null, 6, 'Babysitter');
INSERT INTO wordlist VALUES(null, 6, 'Barber');
INSERT INTO wordlist VALUES(null, 6, 'Bartender');
INSERT INTO wordlist VALUES(null, 6, 'Basement');
INSERT INTO wordlist VALUES(null, 6, 'Bathroom');
INSERT INTO wordlist VALUES(null, 6, 'Bathtub');
INSERT INTO wordlist VALUES(null, 6, 'Bed');
INSERT INTO wordlist VALUES(null, 6, 'Bedroom');
INSERT INTO wordlist VALUES(null, 6, 'Billboard');
INSERT INTO wordlist VALUES(null, 6, 'Black friday');
INSERT INTO wordlist VALUES(null, 6, 'Boarding house');
INSERT INTO wordlist VALUES(null, 6, 'Book');
INSERT INTO wordlist VALUES(null, 6, 'Bookkeeper');
INSERT INTO wordlist VALUES(null, 6, 'Boutique');
INSERT INTO wordlist VALUES(null, 6, 'Briefs');
INSERT INTO wordlist VALUES(null, 6, 'Cab driver');
INSERT INTO wordlist VALUES(null, 6, 'Calculater');
INSERT INTO wordlist VALUES(null, 6, 'Calculator');
INSERT INTO wordlist VALUES(null, 6, 'Candle light dinner');
INSERT INTO wordlist VALUES(null, 6, 'Cane');
INSERT INTO wordlist VALUES(null, 6, 'Cardboard box');
INSERT INTO wordlist VALUES(null, 6, 'Cartoons');
INSERT INTO wordlist VALUES(null, 6, 'Cat nap');
INSERT INTO wordlist VALUES(null, 6, 'Cd');
INSERT INTO wordlist VALUES(null, 6, 'Cell phone');
INSERT INTO wordlist VALUES(null, 6, 'Ceo');
INSERT INTO wordlist VALUES(null, 6, 'Chair');
INSERT INTO wordlist VALUES(null, 6, 'Christmas');
INSERT INTO wordlist VALUES(null, 6, 'Cia');
INSERT INTO wordlist VALUES(null, 6, 'Cloud');
INSERT INTO wordlist VALUES(null, 6, 'Coin-op');
INSERT INTO wordlist VALUES(null, 6, 'Comb');
INSERT INTO wordlist VALUES(null, 6, 'Communication');
INSERT INTO wordlist VALUES(null, 6, 'Conference call');
INSERT INTO wordlist VALUES(null, 6, 'Construction');
INSERT INTO wordlist VALUES(null, 6, 'Conversation');
INSERT INTO wordlist VALUES(null, 6, 'Costco');
INSERT INTO wordlist VALUES(null, 6, 'Couch');
INSERT INTO wordlist VALUES(null, 6, 'Cradit card');
INSERT INTO wordlist VALUES(null, 6, 'Credit card');
INSERT INTO wordlist VALUES(null, 6, 'Day');
INSERT INTO wordlist VALUES(null, 6, 'Day planner');
INSERT INTO wordlist VALUES(null, 6, 'Deck');
INSERT INTO wordlist VALUES(null, 6, 'Delivery');
INSERT INTO wordlist VALUES(null, 6, 'Desicions');
INSERT INTO wordlist VALUES(null, 6, 'Desk');
INSERT INTO wordlist VALUES(null, 6, 'Dice');
INSERT INTO wordlist VALUES(null, 6, 'Dinner and a movie');
INSERT INTO wordlist VALUES(null, 6, 'Diplomat');
INSERT INTO wordlist VALUES(null, 6, 'Doctor');
INSERT INTO wordlist VALUES(null, 6, 'Drive');
INSERT INTO wordlist VALUES(null, 6, 'Driveway');
INSERT INTO wordlist VALUES(null, 6, 'Drunk dial');
INSERT INTO wordlist VALUES(null, 6, 'Dryer');
INSERT INTO wordlist VALUES(null, 6, 'Dust');
INSERT INTO wordlist VALUES(null, 6, 'Dvd');
INSERT INTO wordlist VALUES(null, 6, 'Easter');
INSERT INTO wordlist VALUES(null, 6, 'Editor');
INSERT INTO wordlist VALUES(null, 6, 'Email');
INSERT INTO wordlist VALUES(null, 6, 'Excercise');
INSERT INTO wordlist VALUES(null, 6, 'Exotic dancer');
INSERT INTO wordlist VALUES(null, 6, 'Farmers market');
INSERT INTO wordlist VALUES(null, 6, 'Federal taxes');
INSERT INTO wordlist VALUES(null, 6, 'Fireman');
INSERT INTO wordlist VALUES(null, 6, 'Flashlight');
INSERT INTO wordlist VALUES(null, 6, 'Flea market');
INSERT INTO wordlist VALUES(null, 6, 'Flower');
INSERT INTO wordlist VALUES(null, 6, 'Fork');
INSERT INTO wordlist VALUES(null, 6, 'Frown');
INSERT INTO wordlist VALUES(null, 6, 'Garbage bag');
INSERT INTO wordlist VALUES(null, 6, 'Gardening');
INSERT INTO wordlist VALUES(null, 6, 'Gas');
INSERT INTO wordlist VALUES(null, 6, 'Good friday');
INSERT INTO wordlist VALUES(null, 6, 'Grass');
INSERT INTO wordlist VALUES(null, 6, 'Groceries');
INSERT INTO wordlist VALUES(null, 6, 'Gym');
INSERT INTO wordlist VALUES(null, 6, 'Headphones');
INSERT INTO wordlist VALUES(null, 6, 'Home depot');
INSERT INTO wordlist VALUES(null, 6, 'Honey-do list');
INSERT INTO wordlist VALUES(null, 6, 'Honk the horn');
INSERT INTO wordlist VALUES(null, 6, 'Hospital');
INSERT INTO wordlist VALUES(null, 6, 'Hotel');
INSERT INTO wordlist VALUES(null, 6, 'House');
INSERT INTO wordlist VALUES(null, 6, 'Ikea');
INSERT INTO wordlist VALUES(null, 6, 'Iphone');
INSERT INTO wordlist VALUES(null, 6, 'Jacuzzi');
INSERT INTO wordlist VALUES(null, 6, 'Janitor');
INSERT INTO wordlist VALUES(null, 6, 'Journalist');
INSERT INTO wordlist VALUES(null, 6, 'Judge');
INSERT INTO wordlist VALUES(null, 6, 'Key');
INSERT INTO wordlist VALUES(null, 6, 'Keyword');
INSERT INTO wordlist VALUES(null, 6, 'Kitchen');
INSERT INTO wordlist VALUES(null, 6, 'Kleenex');
INSERT INTO wordlist VALUES(null, 6, 'La-z-boy recliner');
INSERT INTO wordlist VALUES(null, 6, 'Laddre');
INSERT INTO wordlist VALUES(null, 6, 'Lamp');
INSERT INTO wordlist VALUES(null, 6, 'Landscape');
INSERT INTO wordlist VALUES(null, 6, 'Laughter');
INSERT INTO wordlist VALUES(null, 6, 'Lava lamp');
INSERT INTO wordlist VALUES(null, 6, 'Library');
INSERT INTO wordlist VALUES(null, 6, 'Lifeguard');
INSERT INTO wordlist VALUES(null, 6, 'Lighter');
INSERT INTO wordlist VALUES(null, 6, 'Lights');
INSERT INTO wordlist VALUES(null, 6, 'Love');
INSERT INTO wordlist VALUES(null, 6, 'Lunch break');
INSERT INTO wordlist VALUES(null, 6, 'Maid');
INSERT INTO wordlist VALUES(null, 6, 'Mail');
INSERT INTO wordlist VALUES(null, 6, 'Mail box');
INSERT INTO wordlist VALUES(null, 6, 'Map');
INSERT INTO wordlist VALUES(null, 6, 'Massage');
INSERT INTO wordlist VALUES(null, 6, 'Mayor');
INSERT INTO wordlist VALUES(null, 6, 'Meeting');
INSERT INTO wordlist VALUES(null, 6, 'Metabolism');
INSERT INTO wordlist VALUES(null, 6, 'Misunderstanding');
INSERT INTO wordlist VALUES(null, 6, 'Moon');
INSERT INTO wordlist VALUES(null, 6, 'Mortgage');
INSERT INTO wordlist VALUES(null, 6, 'Motorcycle');
INSERT INTO wordlist VALUES(null, 6, 'Mug');
INSERT INTO wordlist VALUES(null, 6, 'Nanny');
INSERT INTO wordlist VALUES(null, 6, 'Newspaper');
INSERT INTO wordlist VALUES(null, 6, 'Night');
INSERT INTO wordlist VALUES(null, 6, 'Nun');
INSERT INTO wordlist VALUES(null, 6, 'Nurse');
INSERT INTO wordlist VALUES(null, 6, 'Online banking');
INSERT INTO wordlist VALUES(null, 6, 'Organize');
INSERT INTO wordlist VALUES(null, 6, 'Painter');
INSERT INTO wordlist VALUES(null, 6, 'Panty hose');
INSERT INTO wordlist VALUES(null, 6, 'Paycheck');
INSERT INTO wordlist VALUES(null, 6, 'Pen');
INSERT INTO wordlist VALUES(null, 6, 'Pencil');
INSERT INTO wordlist VALUES(null, 6, 'Physical therapist');
INSERT INTO wordlist VALUES(null, 6, 'Piggy bank');
INSERT INTO wordlist VALUES(null, 6, 'Plan ahead');
INSERT INTO wordlist VALUES(null, 6, 'Plumber');
INSERT INTO wordlist VALUES(null, 6, 'Poet');
INSERT INTO wordlist VALUES(null, 6, 'Police');
INSERT INTO wordlist VALUES(null, 6, 'Polyester');
INSERT INTO wordlist VALUES(null, 6, 'Pool');
INSERT INTO wordlist VALUES(null, 6, 'Post-it notes');
INSERT INTO wordlist VALUES(null, 6, 'Q-tips');
INSERT INTO wordlist VALUES(null, 6, 'Queen');
INSERT INTO wordlist VALUES(null, 6, 'Retail');
INSERT INTO wordlist VALUES(null, 6, 'Rolodex');
INSERT INTO wordlist VALUES(null, 6, 'Room');
INSERT INTO wordlist VALUES(null, 6, 'Sabbath');
INSERT INTO wordlist VALUES(null, 6, 'Sabbatical');
INSERT INTO wordlist VALUES(null, 6, 'Sailor');
INSERT INTO wordlist VALUES(null, 6, 'Saran wrap');
INSERT INTO wordlist VALUES(null, 6, 'Scarf');
INSERT INTO wordlist VALUES(null, 6, 'Scotch tape');
INSERT INTO wordlist VALUES(null, 6, 'Second-hand smoke');
INSERT INTO wordlist VALUES(null, 6, 'Shoe box');
INSERT INTO wordlist VALUES(null, 6, 'Shoelace');
INSERT INTO wordlist VALUES(null, 6, 'Shopping cart');
INSERT INTO wordlist VALUES(null, 6, 'Shower');
INSERT INTO wordlist VALUES(null, 6, 'Sidewalk');
INSERT INTO wordlist VALUES(null, 6, 'Sink');
INSERT INTO wordlist VALUES(null, 6, 'Siren');
INSERT INTO wordlist VALUES(null, 6, 'Sleepy head');
INSERT INTO wordlist VALUES(null, 6, 'Smile');
INSERT INTO wordlist VALUES(null, 6, 'Snooze button');
INSERT INTO wordlist VALUES(null, 6, 'Snow');
INSERT INTO wordlist VALUES(null, 6, 'Soap');
INSERT INTO wordlist VALUES(null, 6, 'Spa');
INSERT INTO wordlist VALUES(null, 6, 'Speech');
INSERT INTO wordlist VALUES(null, 6, 'Spoon');
INSERT INTO wordlist VALUES(null, 6, 'Spring break');
INSERT INTO wordlist VALUES(null, 6, 'Star');
INSERT INTO wordlist VALUES(null, 6, 'Step ladder');
INSERT INTO wordlist VALUES(null, 6, 'Stock market');
INSERT INTO wordlist VALUES(null, 6, 'Stop light');
INSERT INTO wordlist VALUES(null, 6, 'Stunt double');
INSERT INTO wordlist VALUES(null, 6, 'Sun');
INSERT INTO wordlist VALUES(null, 6, 'Sunscreen');
INSERT INTO wordlist VALUES(null, 6, 'Supermarket');
INSERT INTO wordlist VALUES(null, 6, 'T-shirt');
INSERT INTO wordlist VALUES(null, 6, 'Textbook');
INSERT INTO wordlist VALUES(null, 6, 'Tgif');
INSERT INTO wordlist VALUES(null, 6, 'Thirft store');
INSERT INTO wordlist VALUES(null, 6, 'Thunder and lightening');
INSERT INTO wordlist VALUES(null, 6, 'Toothbrush');
INSERT INTO wordlist VALUES(null, 6, 'Toothpaste');
INSERT INTO wordlist VALUES(null, 6, 'Tractor');
INSERT INTO wordlist VALUES(null, 6, 'Traffic');
INSERT INTO wordlist VALUES(null, 6, 'Trash can');
INSERT INTO wordlist VALUES(null, 6, 'Tree');
INSERT INTO wordlist VALUES(null, 6, 'Truck');
INSERT INTO wordlist VALUES(null, 6, 'Truck driver');
INSERT INTO wordlist VALUES(null, 6, 'Tupperware');
INSERT INTO wordlist VALUES(null, 6, 'Type');
INSERT INTO wordlist VALUES(null, 6, 'Typewriter');
INSERT INTO wordlist VALUES(null, 6, 'Typing');
INSERT INTO wordlist VALUES(null, 6, 'U-haul');
INSERT INTO wordlist VALUES(null, 6, 'Undertaker');
INSERT INTO wordlist VALUES(null, 6, 'Underwire');
INSERT INTO wordlist VALUES(null, 6, 'Urban planner');
INSERT INTO wordlist VALUES(null, 6, 'Vacuum');
INSERT INTO wordlist VALUES(null, 6, 'Venetian blinds');
INSERT INTO wordlist VALUES(null, 6, 'Vons');
INSERT INTO wordlist VALUES(null, 6, 'Waiting in line');
INSERT INTO wordlist VALUES(null, 6, 'Wal-mart');
INSERT INTO wordlist VALUES(null, 6, 'Wallet');
INSERT INTO wordlist VALUES(null, 6, 'Washer');
INSERT INTO wordlist VALUES(null, 6, 'Washing machine');
INSERT INTO wordlist VALUES(null, 6, 'Water bottle');
INSERT INTO wordlist VALUES(null, 6, 'Wd-40');
INSERT INTO wordlist VALUES(null, 6, 'Weatherman');
INSERT INTO wordlist VALUES(null, 6, 'Website');
INSERT INTO wordlist VALUES(null, 6, 'Wedding ring');
INSERT INTO wordlist VALUES(null, 6, 'White-out');
INSERT INTO wordlist VALUES(null, 6, 'Work');
INSERT INTO wordlist VALUES(null, 6, 'Work overtime');
INSERT INTO wordlist VALUES(null, 6, 'Writer');
INSERT INTO wordlist VALUES(null, 6, 'Xbox');
INSERT INTO wordlist VALUES(null, 6, 'Yawn');
INSERT INTO wordlist VALUES(null, 6, 'Yoga mat');
INSERT INTO wordlist VALUES(null, 6, 'Zipper');
INSERT INTO wordlist VALUES(null, 6, 'Zoo keeper');
INSERT INTO wordlist VALUES(null, 7, '2% milk');
INSERT INTO wordlist VALUES(null, 7, 'Acai');
INSERT INTO wordlist VALUES(null, 7, 'Agave');
INSERT INTO wordlist VALUES(null, 7, 'Alcohol');
INSERT INTO wordlist VALUES(null, 7, 'Angel food cake');
INSERT INTO wordlist VALUES(null, 7, 'Apple');
INSERT INTO wordlist VALUES(null, 7, 'Apple juice');
INSERT INTO wordlist VALUES(null, 7, 'Apple pie');
INSERT INTO wordlist VALUES(null, 7, 'Avocado');
INSERT INTO wordlist VALUES(null, 7, 'Bacon');
INSERT INTO wordlist VALUES(null, 7, 'Balsamic vinegar');
INSERT INTO wordlist VALUES(null, 7, 'Balut');
INSERT INTO wordlist VALUES(null, 7, 'Banana cream pie');
INSERT INTO wordlist VALUES(null, 7, 'Banana split');
INSERT INTO wordlist VALUES(null, 7, 'Beans');
INSERT INTO wordlist VALUES(null, 7, 'Beef');
INSERT INTO wordlist VALUES(null, 7, 'Beef stew');
INSERT INTO wordlist VALUES(null, 7, 'Beets');
INSERT INTO wordlist VALUES(null, 7, 'Birds nest soup');
INSERT INTO wordlist VALUES(null, 7, 'Biscotti');
INSERT INTO wordlist VALUES(null, 7, 'Black beans');
INSERT INTO wordlist VALUES(null, 7, 'Black rice');
INSERT INTO wordlist VALUES(null, 7, 'Blt');
INSERT INTO wordlist VALUES(null, 7, 'Boba tea');
INSERT INTO wordlist VALUES(null, 7, 'Bok choy');
INSERT INTO wordlist VALUES(null, 7, 'Bratwurst');
INSERT INTO wordlist VALUES(null, 7, 'Bread');
INSERT INTO wordlist VALUES(null, 7, 'Breakfast');
INSERT INTO wordlist VALUES(null, 7, 'Brie');
INSERT INTO wordlist VALUES(null, 7, 'Brunch');
INSERT INTO wordlist VALUES(null, 7, 'Buger king');
INSERT INTO wordlist VALUES(null, 7, 'Burger king');
INSERT INTO wordlist VALUES(null, 7, 'Butter');
INSERT INTO wordlist VALUES(null, 7, 'Butternut squash');
INSERT INTO wordlist VALUES(null, 7, 'Cabbage');
INSERT INTO wordlist VALUES(null, 7, 'Cafe latte');
INSERT INTO wordlist VALUES(null, 7, 'Campbells soup');
INSERT INTO wordlist VALUES(null, 7, 'Canadian bacon');
INSERT INTO wordlist VALUES(null, 7, 'Cappucino');
INSERT INTO wordlist VALUES(null, 7, 'Carmels');
INSERT INTO wordlist VALUES(null, 7, 'Carne asada burrito');
INSERT INTO wordlist VALUES(null, 7, 'Carob');
INSERT INTO wordlist VALUES(null, 7, 'Carrot');
INSERT INTO wordlist VALUES(null, 7, 'Carrot juice');
INSERT INTO wordlist VALUES(null, 7, 'Caviar');
INSERT INTO wordlist VALUES(null, 7, 'Cereal');
INSERT INTO wordlist VALUES(null, 7, 'Ceviche');
INSERT INTO wordlist VALUES(null, 7, 'Chardonnay');
INSERT INTO wordlist VALUES(null, 7, 'Cheese');
INSERT INTO wordlist VALUES(null, 7, 'Cheese in a can');
INSERT INTO wordlist VALUES(null, 7, 'Cheez-its');
INSERT INTO wordlist VALUES(null, 7, 'Chesnuts');
INSERT INTO wordlist VALUES(null, 7, 'Chestnuts');
INSERT INTO wordlist VALUES(null, 7, 'Chewing gum');
INSERT INTO wordlist VALUES(null, 7, 'Chex mix');
INSERT INTO wordlist VALUES(null, 7, 'Chicken');
INSERT INTO wordlist VALUES(null, 7, 'Chicken of the sea');
INSERT INTO wordlist VALUES(null, 7, 'Chicken salad');
INSERT INTO wordlist VALUES(null, 7, 'Chinese food');
INSERT INTO wordlist VALUES(null, 7, 'Chips');
INSERT INTO wordlist VALUES(null, 7, 'Chocolate chip cookies');
INSERT INTO wordlist VALUES(null, 7, 'Cinnamon');
INSERT INTO wordlist VALUES(null, 7, 'Cinnamon rolls');
INSERT INTO wordlist VALUES(null, 7, 'Clam chowder');
INSERT INTO wordlist VALUES(null, 7, 'Cloves');
INSERT INTO wordlist VALUES(null, 7, 'Coca colla');
INSERT INTO wordlist VALUES(null, 7, 'Coffee');
INSERT INTO wordlist VALUES(null, 7, 'Coke');
INSERT INTO wordlist VALUES(null, 7, 'Cold stone');
INSERT INTO wordlist VALUES(null, 7, 'Collard greens');
INSERT INTO wordlist VALUES(null, 7, 'Cookie dough');
INSERT INTO wordlist VALUES(null, 7, 'Corn');
INSERT INTO wordlist VALUES(null, 7, 'Corn bread');
INSERT INTO wordlist VALUES(null, 7, 'Corn dogs');
INSERT INTO wordlist VALUES(null, 7, 'Cornish game hen');
INSERT INTO wordlist VALUES(null, 7, 'Cow tongue');
INSERT INTO wordlist VALUES(null, 7, 'Cranberry sauce');
INSERT INTO wordlist VALUES(null, 7, 'Cream cheese');
INSERT INTO wordlist VALUES(null, 7, 'Cucumber');
INSERT INTO wordlist VALUES(null, 7, 'Curry');
INSERT INTO wordlist VALUES(null, 7, 'Decaf coffee');
INSERT INTO wordlist VALUES(null, 7, 'Del taco');
INSERT INTO wordlist VALUES(null, 7, 'Desert');
INSERT INTO wordlist VALUES(null, 7, 'Dijon mustard');
INSERT INTO wordlist VALUES(null, 7, 'Dinner');
INSERT INTO wordlist VALUES(null, 7, 'Dinner roll');
INSERT INTO wordlist VALUES(null, 7, 'Dr. pepper');
INSERT INTO wordlist VALUES(null, 7, 'Dried cherries');
INSERT INTO wordlist VALUES(null, 7, 'Dulse');
INSERT INTO wordlist VALUES(null, 7, 'Durian');
INSERT INTO wordlist VALUES(null, 7, 'Egg');
INSERT INTO wordlist VALUES(null, 7, 'Egg salad');
INSERT INTO wordlist VALUES(null, 7, 'Electricity');
INSERT INTO wordlist VALUES(null, 7, 'English muffin');
INSERT INTO wordlist VALUES(null, 7, 'Falafal');
INSERT INTO wordlist VALUES(null, 7, 'Feta');
INSERT INTO wordlist VALUES(null, 7, 'Fetticine alfredo');
INSERT INTO wordlist VALUES(null, 7, 'Fig newtons');
INSERT INTO wordlist VALUES(null, 7, 'Figs');
INSERT INTO wordlist VALUES(null, 7, 'Filet mignon');
INSERT INTO wordlist VALUES(null, 7, 'Flour');
INSERT INTO wordlist VALUES(null, 7, 'Fortune cookie');
INSERT INTO wordlist VALUES(null, 7, 'Frappucino');
INSERT INTO wordlist VALUES(null, 7, 'Fried green tomatoes');
INSERT INTO wordlist VALUES(null, 7, 'Fried twinkie');
INSERT INTO wordlist VALUES(null, 7, 'Fruit loops');
INSERT INTO wordlist VALUES(null, 7, 'Garbanzo beans');
INSERT INTO wordlist VALUES(null, 7, 'Gardettos');
INSERT INTO wordlist VALUES(null, 7, 'Garlic');
INSERT INTO wordlist VALUES(null, 7, 'Gator-aid');
INSERT INTO wordlist VALUES(null, 7, 'Ginger');
INSERT INTO wordlist VALUES(null, 7, 'Gingerbread house');
INSERT INTO wordlist VALUES(null, 7, 'Glog');
INSERT INTO wordlist VALUES(null, 7, 'Goji berries');
INSERT INTO wordlist VALUES(null, 7, 'Gorgonzola');
INSERT INTO wordlist VALUES(null, 7, 'Granola');
INSERT INTO wordlist VALUES(null, 7, 'Grape');
INSERT INTO wordlist VALUES(null, 7, 'Grapes');
INSERT INTO wordlist VALUES(null, 7, 'Gravy');
INSERT INTO wordlist VALUES(null, 7, 'Green bell pepper');
INSERT INTO wordlist VALUES(null, 7, 'Grilled chicken');
INSERT INTO wordlist VALUES(null, 7, 'Grits');
INSERT INTO wordlist VALUES(null, 7, 'H2o');
INSERT INTO wordlist VALUES(null, 7, 'Ham');
INSERT INTO wordlist VALUES(null, 7, 'Hamburger');
INSERT INTO wordlist VALUES(null, 7, 'Hash browns');
INSERT INTO wordlist VALUES(null, 7, 'Honey');
INSERT INTO wordlist VALUES(null, 7, 'Horseradish');
INSERT INTO wordlist VALUES(null, 7, 'Hot cross buns');
INSERT INTO wordlist VALUES(null, 7, 'Hot sake');
INSERT INTO wordlist VALUES(null, 7, 'Hotdog');
INSERT INTO wordlist VALUES(null, 7, 'Hummus');
INSERT INTO wordlist VALUES(null, 7, 'Ice cream sundae');
INSERT INTO wordlist VALUES(null, 7, 'Iced tea');
INSERT INTO wordlist VALUES(null, 7, 'Jack-in-the-box');
INSERT INTO wordlist VALUES(null, 7, 'Jackfruit');
INSERT INTO wordlist VALUES(null, 7, 'Jalapeno');
INSERT INTO wordlist VALUES(null, 7, 'Jalepeno pepper');
INSERT INTO wordlist VALUES(null, 7, 'Jam');
INSERT INTO wordlist VALUES(null, 7, 'Jamba juice');
INSERT INTO wordlist VALUES(null, 7, 'Jelly');
INSERT INTO wordlist VALUES(null, 7, 'Jenny craig');
INSERT INTO wordlist VALUES(null, 7, 'Juice');
INSERT INTO wordlist VALUES(null, 7, 'Kale');
INSERT INTO wordlist VALUES(null, 7, 'Ketchup');
INSERT INTO wordlist VALUES(null, 7, 'Kidney beans');
INSERT INTO wordlist VALUES(null, 7, 'Kim chee');
INSERT INTO wordlist VALUES(null, 7, 'Kombucha');
INSERT INTO wordlist VALUES(null, 7, 'Kool-aid');
INSERT INTO wordlist VALUES(null, 7, 'Kraft mac and cheese');
INSERT INTO wordlist VALUES(null, 7, 'Lasagna');
INSERT INTO wordlist VALUES(null, 7, 'Latte');
INSERT INTO wordlist VALUES(null, 7, 'Left overs');
INSERT INTO wordlist VALUES(null, 7, 'Lemon');
INSERT INTO wordlist VALUES(null, 7, 'Lettuce');
INSERT INTO wordlist VALUES(null, 7, 'Lima beans');
INSERT INTO wordlist VALUES(null, 7, 'Lunch');
INSERT INTO wordlist VALUES(null, 7, 'Maple syrup');
INSERT INTO wordlist VALUES(null, 7, 'Margarine');
INSERT INTO wordlist VALUES(null, 7, 'Marshmallows');
INSERT INTO wordlist VALUES(null, 7, 'Martini');
INSERT INTO wordlist VALUES(null, 7, 'Matzo');
INSERT INTO wordlist VALUES(null, 7, 'Mayonnaise');
INSERT INTO wordlist VALUES(null, 7, 'Mcdonalds');
INSERT INTO wordlist VALUES(null, 7, 'Meatloaf');
INSERT INTO wordlist VALUES(null, 7, 'Merlot');
INSERT INTO wordlist VALUES(null, 7, 'Milk');
INSERT INTO wordlist VALUES(null, 7, 'Milk shake');
INSERT INTO wordlist VALUES(null, 7, 'Miso');
INSERT INTO wordlist VALUES(null, 7, 'Mocha');
INSERT INTO wordlist VALUES(null, 7, 'Moonpies');
INSERT INTO wordlist VALUES(null, 7, 'Mr. pibb');
INSERT INTO wordlist VALUES(null, 7, 'Muffins');
INSERT INTO wordlist VALUES(null, 7, 'Mushroom');
INSERT INTO wordlist VALUES(null, 7, 'Mustard');
INSERT INTO wordlist VALUES(null, 7, 'New york strip');
INSERT INTO wordlist VALUES(null, 7, 'Nutmeg');
INSERT INTO wordlist VALUES(null, 7, 'Oatmeal');
INSERT INTO wordlist VALUES(null, 7, 'Olive oil');
INSERT INTO wordlist VALUES(null, 7, 'Onion rings');
INSERT INTO wordlist VALUES(null, 7, 'Orange');
INSERT INTO wordlist VALUES(null, 7, 'Orange juice');
INSERT INTO wordlist VALUES(null, 7, 'Otter pops');
INSERT INTO wordlist VALUES(null, 7, 'Pad thai');
INSERT INTO wordlist VALUES(null, 7, 'Pancake');
INSERT INTO wordlist VALUES(null, 7, 'Papaya');
INSERT INTO wordlist VALUES(null, 7, 'Pasta');
INSERT INTO wordlist VALUES(null, 7, 'Peach');
INSERT INTO wordlist VALUES(null, 7, 'Peanut');
INSERT INTO wordlist VALUES(null, 7, 'Penicillin');
INSERT INTO wordlist VALUES(null, 7, 'Pepper');
INSERT INTO wordlist VALUES(null, 7, 'Peppercorns');
INSERT INTO wordlist VALUES(null, 7, 'Pepperoni');
INSERT INTO wordlist VALUES(null, 7, 'Pepsi');
INSERT INTO wordlist VALUES(null, 7, 'Pesto');
INSERT INTO wordlist VALUES(null, 7, 'Pez candy');
INSERT INTO wordlist VALUES(null, 7, 'Pho');
INSERT INTO wordlist VALUES(null, 7, 'Pine nuts');
INSERT INTO wordlist VALUES(null, 7, 'Pinot noir');
INSERT INTO wordlist VALUES(null, 7, 'Pita bread');
INSERT INTO wordlist VALUES(null, 7, 'Pizza');
INSERT INTO wordlist VALUES(null, 7, 'Plums');
INSERT INTO wordlist VALUES(null, 7, 'Pomegranate');
INSERT INTO wordlist VALUES(null, 7, 'Pop tart');
INSERT INTO wordlist VALUES(null, 7, 'Pop tarts');
INSERT INTO wordlist VALUES(null, 7, 'Portobello burger');
INSERT INTO wordlist VALUES(null, 7, 'Pot roast');
INSERT INTO wordlist VALUES(null, 7, 'Potato');
INSERT INTO wordlist VALUES(null, 7, 'Potatoe pancakes');
INSERT INTO wordlist VALUES(null, 7, 'Pound cake');
INSERT INTO wordlist VALUES(null, 7, 'Pretzel');
INSERT INTO wordlist VALUES(null, 7, 'Prozac');
INSERT INTO wordlist VALUES(null, 7, 'Pumpkin pie');
INSERT INTO wordlist VALUES(null, 7, 'Quinoa');
INSERT INTO wordlist VALUES(null, 7, 'Raisins');
INSERT INTO wordlist VALUES(null, 7, 'Ramen noodles');
INSERT INTO wordlist VALUES(null, 7, 'Red bell pepper');
INSERT INTO wordlist VALUES(null, 7, 'Red bull');
INSERT INTO wordlist VALUES(null, 7, 'Red pepper');
INSERT INTO wordlist VALUES(null, 7, 'Refried beens');
INSERT INTO wordlist VALUES(null, 7, 'Relish');
INSERT INTO wordlist VALUES(null, 7, 'Rib eye steak');
INSERT INTO wordlist VALUES(null, 7, 'Rice');
INSERT INTO wordlist VALUES(null, 7, 'Rice krispies');
INSERT INTO wordlist VALUES(null, 7, 'Romaine lettuce');
INSERT INTO wordlist VALUES(null, 7, 'Sage');
INSERT INTO wordlist VALUES(null, 7, 'Salad dressing');
INSERT INTO wordlist VALUES(null, 7, 'Salami');
INSERT INTO wordlist VALUES(null, 7, 'Salt');
INSERT INTO wordlist VALUES(null, 7, 'Sardines');
INSERT INTO wordlist VALUES(null, 7, 'Sausage');
INSERT INTO wordlist VALUES(null, 7, 'Scotch');
INSERT INTO wordlist VALUES(null, 7, 'Seed');
INSERT INTO wordlist VALUES(null, 7, 'Shitake mushrooms');
INSERT INTO wordlist VALUES(null, 7, 'Shredded wheat');
INSERT INTO wordlist VALUES(null, 7, 'Sirloin');
INSERT INTO wordlist VALUES(null, 7, 'Smoothie');
INSERT INTO wordlist VALUES(null, 7, 'Snapple');
INSERT INTO wordlist VALUES(null, 7, 'Soft shell crab roll');
INSERT INTO wordlist VALUES(null, 7, 'Soy milk');
INSERT INTO wordlist VALUES(null, 7, 'Soy sauce');
INSERT INTO wordlist VALUES(null, 7, 'Spaghetti');
INSERT INTO wordlist VALUES(null, 7, 'Special k');
INSERT INTO wordlist VALUES(null, 7, 'Spinach');
INSERT INTO wordlist VALUES(null, 7, 'Spirulina');
INSERT INTO wordlist VALUES(null, 7, 'Spork');
INSERT INTO wordlist VALUES(null, 7, 'Squash');
INSERT INTO wordlist VALUES(null, 7, 'Starbucks');
INSERT INTO wordlist VALUES(null, 7, 'Steak');
INSERT INTO wordlist VALUES(null, 7, 'Stir fry');
INSERT INTO wordlist VALUES(null, 7, 'Sugar');
INSERT INTO wordlist VALUES(null, 7, 'Sugar cookies');
INSERT INTO wordlist VALUES(null, 7, 'Surf and turf');
INSERT INTO wordlist VALUES(null, 7, 'Sushi');
INSERT INTO wordlist VALUES(null, 7, 'Swiss chard');
INSERT INTO wordlist VALUES(null, 7, 'Tater tots');
INSERT INTO wordlist VALUES(null, 7, 'Tempeh');
INSERT INTO wordlist VALUES(null, 7, 'Tenderloin');
INSERT INTO wordlist VALUES(null, 7, 'Tequila');
INSERT INTO wordlist VALUES(null, 7, 'Thousand island dressing');
INSERT INTO wordlist VALUES(null, 7, 'Tomato');
INSERT INTO wordlist VALUES(null, 7, 'Triscuts');
INSERT INTO wordlist VALUES(null, 7, 'Truffles');
INSERT INTO wordlist VALUES(null, 7, 'Tuna on toast');
INSERT INTO wordlist VALUES(null, 7, 'Turkey and stuffing');
INSERT INTO wordlist VALUES(null, 7, 'Turmeric');
INSERT INTO wordlist VALUES(null, 7, 'Vanilla');
INSERT INTO wordlist VALUES(null, 7, 'Veal');
INSERT INTO wordlist VALUES(null, 7, 'Vegemite');
INSERT INTO wordlist VALUES(null, 7, 'Velveeta');
INSERT INTO wordlist VALUES(null, 7, 'Walnuts');
INSERT INTO wordlist VALUES(null, 7, 'Wasabi');
INSERT INTO wordlist VALUES(null, 7, 'Water');
INSERT INTO wordlist VALUES(null, 7, 'Watermellon');
INSERT INTO wordlist VALUES(null, 7, 'Watermelon');
INSERT INTO wordlist VALUES(null, 7, 'Weight watchers');
INSERT INTO wordlist VALUES(null, 7, 'Wheat thins');
INSERT INTO wordlist VALUES(null, 7, 'White rice');
INSERT INTO wordlist VALUES(null, 7, 'Wild rice');
INSERT INTO wordlist VALUES(null, 7, 'Wine');
INSERT INTO wordlist VALUES(null, 7, 'Zuchinni');
INSERT INTO wordlist VALUES(null, 8, '1099');
INSERT INTO wordlist VALUES(null, 8, 'Adolescent  ');
INSERT INTO wordlist VALUES(null, 8, 'Adoption');
INSERT INTO wordlist VALUES(null, 8, 'Arm');
INSERT INTO wordlist VALUES(null, 8, 'Ashtanga yoga');
INSERT INTO wordlist VALUES(null, 8, 'Astrology');
INSERT INTO wordlist VALUES(null, 8, 'Aunt');
INSERT INTO wordlist VALUES(null, 8, 'Autumn');
INSERT INTO wordlist VALUES(null, 8, 'Avalance');
INSERT INTO wordlist VALUES(null, 8, 'Baby');
INSERT INTO wordlist VALUES(null, 8, 'Ball');
INSERT INTO wordlist VALUES(null, 8, 'Balloon');
INSERT INTO wordlist VALUES(null, 8, 'Bank');
INSERT INTO wordlist VALUES(null, 8, 'Bank of america');
INSERT INTO wordlist VALUES(null, 8, 'Beard');
INSERT INTO wordlist VALUES(null, 8, 'Biological');
INSERT INTO wordlist VALUES(null, 8, 'Blog');
INSERT INTO wordlist VALUES(null, 8, 'Bottle');
INSERT INTO wordlist VALUES(null, 8, 'Brick');
INSERT INTO wordlist VALUES(null, 8, 'Bridezilla');
INSERT INTO wordlist VALUES(null, 8, 'Brother');
INSERT INTO wordlist VALUES(null, 8, 'Brother-in-law');
INSERT INTO wordlist VALUES(null, 8, 'Building');
INSERT INTO wordlist VALUES(null, 8, 'Calendar');
INSERT INTO wordlist VALUES(null, 8, 'Camera');
INSERT INTO wordlist VALUES(null, 8, 'Can');
INSERT INTO wordlist VALUES(null, 8, 'Cankle');
INSERT INTO wordlist VALUES(null, 8, 'Carpet');
INSERT INTO wordlist VALUES(null, 8, 'Carwash');
INSERT INTO wordlist VALUES(null, 8, 'Certified organic');
INSERT INTO wordlist VALUES(null, 8, 'Child');
INSERT INTO wordlist VALUES(null, 8, 'Church');
INSERT INTO wordlist VALUES(null, 8, 'Clock');
INSERT INTO wordlist VALUES(null, 8, 'Closet');
INSERT INTO wordlist VALUES(null, 8, 'Compressed air');
INSERT INTO wordlist VALUES(null, 8, 'Cousin');
INSERT INTO wordlist VALUES(null, 8, 'Crayon');
INSERT INTO wordlist VALUES(null, 8, 'Cuddle');
INSERT INTO wordlist VALUES(null, 8, 'Darth vader');
INSERT INTO wordlist VALUES(null, 8, 'Database');
INSERT INTO wordlist VALUES(null, 8, 'Date');
INSERT INTO wordlist VALUES(null, 8, 'Daughter');
INSERT INTO wordlist VALUES(null, 8, 'Drill');
INSERT INTO wordlist VALUES(null, 8, 'Ear');
INSERT INTO wordlist VALUES(null, 8, 'Engagement');
INSERT INTO wordlist VALUES(null, 8, 'Engagement ring');
INSERT INTO wordlist VALUES(null, 8, 'Epsom salt');
INSERT INTO wordlist VALUES(null, 8, 'Essay');
INSERT INTO wordlist VALUES(null, 8, 'Facial hair');
INSERT INTO wordlist VALUES(null, 8, 'Fall');
INSERT INTO wordlist VALUES(null, 8, 'Father');
INSERT INTO wordlist VALUES(null, 8, 'Female');
INSERT INTO wordlist VALUES(null, 8, 'Fingernail');
INSERT INTO wordlist VALUES(null, 8, 'Flip flop slippers');
INSERT INTO wordlist VALUES(null, 8, 'Foot');
INSERT INTO wordlist VALUES(null, 8, 'Forest');
INSERT INTO wordlist VALUES(null, 8, 'Fortune teller');
INSERT INTO wordlist VALUES(null, 8, 'Free-gan');
INSERT INTO wordlist VALUES(null, 8, 'Garbage');
INSERT INTO wordlist VALUES(null, 8, 'Gene');
INSERT INTO wordlist VALUES(null, 8, 'Go postal');
INSERT INTO wordlist VALUES(null, 8, 'Grandfather');
INSERT INTO wordlist VALUES(null, 8, 'Grandmother');
INSERT INTO wordlist VALUES(null, 8, 'Great aunt');
INSERT INTO wordlist VALUES(null, 8, 'Great uncle');
INSERT INTO wordlist VALUES(null, 8, 'Gremlin');
INSERT INTO wordlist VALUES(null, 8, 'Grenade');
INSERT INTO wordlist VALUES(null, 8, 'Grocery');
INSERT INTO wordlist VALUES(null, 8, 'Gun');
INSERT INTO wordlist VALUES(null, 8, 'Hammer');
INSERT INTO wordlist VALUES(null, 8, 'Hand');
INSERT INTO wordlist VALUES(null, 8, 'Hand-me-downs');
INSERT INTO wordlist VALUES(null, 8, 'Head');
INSERT INTO wordlist VALUES(null, 8, 'Hit-and-run');
INSERT INTO wordlist VALUES(null, 8, 'Horoscope');
INSERT INTO wordlist VALUES(null, 8, 'Infant');
INSERT INTO wordlist VALUES(null, 8, 'Inheritance');
INSERT INTO wordlist VALUES(null, 8, 'Jargon');
INSERT INTO wordlist VALUES(null, 8, 'Keyboard');
INSERT INTO wordlist VALUES(null, 8, 'Kinship');
INSERT INTO wordlist VALUES(null, 8, 'Kudzu');
INSERT INTO wordlist VALUES(null, 8, 'Lab');
INSERT INTO wordlist VALUES(null, 8, 'Laptop');
INSERT INTO wordlist VALUES(null, 8, 'Latex');
INSERT INTO wordlist VALUES(null, 8, 'Lawyer ');
INSERT INTO wordlist VALUES(null, 8, 'Leg');
INSERT INTO wordlist VALUES(null, 8, 'Lmao');
INSERT INTO wordlist VALUES(null, 8, 'Lol');
INSERT INTO wordlist VALUES(null, 8, 'Lumber');
INSERT INTO wordlist VALUES(null, 8, 'Male');
INSERT INTO wordlist VALUES(null, 8, 'Man');
INSERT INTO wordlist VALUES(null, 8, 'Marriage');
INSERT INTO wordlist VALUES(null, 8, 'Married');
INSERT INTO wordlist VALUES(null, 8, 'Maternal');
INSERT INTO wordlist VALUES(null, 8, 'Maternity');
INSERT INTO wordlist VALUES(null, 8, 'Math');
INSERT INTO wordlist VALUES(null, 8, 'Military');
INSERT INTO wordlist VALUES(null, 8, 'Missle');
INSERT INTO wordlist VALUES(null, 8, 'Mother');
INSERT INTO wordlist VALUES(null, 8, 'Nail');
INSERT INTO wordlist VALUES(null, 8, 'Napkin');
INSERT INTO wordlist VALUES(null, 8, 'Neck');
INSERT INTO wordlist VALUES(null, 8, 'Nephew');
INSERT INTO wordlist VALUES(null, 8, 'Niece');
INSERT INTO wordlist VALUES(null, 8, 'Nose');
INSERT INTO wordlist VALUES(null, 8, 'Nuclear family');
INSERT INTO wordlist VALUES(null, 8, 'Ocean');
INSERT INTO wordlist VALUES(null, 8, 'Octuplets');
INSERT INTO wordlist VALUES(null, 8, 'Office');
INSERT INTO wordlist VALUES(null, 8, 'Okie dokie');
INSERT INTO wordlist VALUES(null, 8, 'Paint');
INSERT INTO wordlist VALUES(null, 8, 'Pandoras box');
INSERT INTO wordlist VALUES(null, 8, 'Pants');
INSERT INTO wordlist VALUES(null, 8, 'Paper');
INSERT INTO wordlist VALUES(null, 8, 'Photo');
INSERT INTO wordlist VALUES(null, 8, 'Picture frame');
INSERT INTO wordlist VALUES(null, 8, 'Pillow fight');
INSERT INTO wordlist VALUES(null, 8, 'Pimple');
INSERT INTO wordlist VALUES(null, 8, 'Pipe');
INSERT INTO wordlist VALUES(null, 8, 'Pistol');
INSERT INTO wordlist VALUES(null, 8, 'Planet');
INSERT INTO wordlist VALUES(null, 8, 'Poster');
INSERT INTO wordlist VALUES(null, 8, 'Pregnant');
INSERT INTO wordlist VALUES(null, 8, 'Pressure');
INSERT INTO wordlist VALUES(null, 8, 'Qi gong');
INSERT INTO wordlist VALUES(null, 8, 'Recycle');
INSERT INTO wordlist VALUES(null, 8, 'Remote');
INSERT INTO wordlist VALUES(null, 8, 'Rocket');
INSERT INTO wordlist VALUES(null, 8, 'Saw');
INSERT INTO wordlist VALUES(null, 8, 'School');
INSERT INTO wordlist VALUES(null, 8, 'Science');
INSERT INTO wordlist VALUES(null, 8, 'Screen');
INSERT INTO wordlist VALUES(null, 8, 'Screw');
INSERT INTO wordlist VALUES(null, 8, 'Shirt');
INSERT INTO wordlist VALUES(null, 8, 'Sign language');
INSERT INTO wordlist VALUES(null, 8, 'Sister');
INSERT INTO wordlist VALUES(null, 8, 'Sister-in-law');
INSERT INTO wordlist VALUES(null, 8, 'Sneeze');
INSERT INTO wordlist VALUES(null, 8, 'Sniper');
INSERT INTO wordlist VALUES(null, 8, 'Son');
INSERT INTO wordlist VALUES(null, 8, 'Space');
INSERT INTO wordlist VALUES(null, 8, 'Spam');
INSERT INTO wordlist VALUES(null, 8, 'Spring');
INSERT INTO wordlist VALUES(null, 8, 'Stepfather');
INSERT INTO wordlist VALUES(null, 8, 'Stepmother');
INSERT INTO wordlist VALUES(null, 8, 'Stone');
INSERT INTO wordlist VALUES(null, 8, 'Summer');
INSERT INTO wordlist VALUES(null, 8, 'Swamp');
INSERT INTO wordlist VALUES(null, 8, 'Talk to the hand');
INSERT INTO wordlist VALUES(null, 8, 'Tank');
INSERT INTO wordlist VALUES(null, 8, 'Tea light candle');
INSERT INTO wordlist VALUES(null, 8, 'Teen');
INSERT INTO wordlist VALUES(null, 8, 'Teenager');
INSERT INTO wordlist VALUES(null, 8, 'Television');
INSERT INTO wordlist VALUES(null, 8, 'Throat');
INSERT INTO wordlist VALUES(null, 8, 'Torso');
INSERT INTO wordlist VALUES(null, 8, 'Tot');
INSERT INTO wordlist VALUES(null, 8, 'Trench');
INSERT INTO wordlist VALUES(null, 8, 'Triplets');
INSERT INTO wordlist VALUES(null, 8, 'Troll');
INSERT INTO wordlist VALUES(null, 8, 'Tube');
INSERT INTO wordlist VALUES(null, 8, 'Twins');
INSERT INTO wordlist VALUES(null, 8, 'Uncle');
INSERT INTO wordlist VALUES(null, 8, 'Universe');
INSERT INTO wordlist VALUES(null, 8, 'Usb cord');
INSERT INTO wordlist VALUES(null, 8, 'Valentines day');
INSERT INTO wordlist VALUES(null, 8, 'Voicemail');
INSERT INTO wordlist VALUES(null, 8, 'W-2');
INSERT INTO wordlist VALUES(null, 8, 'Wall-e');
INSERT INTO wordlist VALUES(null, 8, 'Watch');
INSERT INTO wordlist VALUES(null, 8, 'Window');
INSERT INTO wordlist VALUES(null, 8, 'Woman');
INSERT INTO wordlist VALUES(null, 8, 'Wood');
INSERT INTO wordlist VALUES(null, 8, 'World');
INSERT INTO wordlist VALUES(null, 8, 'Yelp');
INSERT INTO wordlist VALUES(null, 9, 'Aardvark');
INSERT INTO wordlist VALUES(null, 9, 'Alligator');
INSERT INTO wordlist VALUES(null, 9, 'Ant');
INSERT INTO wordlist VALUES(null, 9, 'Antelope');
INSERT INTO wordlist VALUES(null, 9, 'Bat');
INSERT INTO wordlist VALUES(null, 9, 'Bear');
INSERT INTO wordlist VALUES(null, 9, 'Beaver');
INSERT INTO wordlist VALUES(null, 9, 'Bee');
INSERT INTO wordlist VALUES(null, 9, 'Beetle');
INSERT INTO wordlist VALUES(null, 9, 'Big horn sheep');
INSERT INTO wordlist VALUES(null, 9, 'Bird');
INSERT INTO wordlist VALUES(null, 9, 'Bison');
INSERT INTO wordlist VALUES(null, 9, 'Black widow');
INSERT INTO wordlist VALUES(null, 9, 'Blue whale');
INSERT INTO wordlist VALUES(null, 9, 'Buffalo');
INSERT INTO wordlist VALUES(null, 9, 'Bumblebee bat');
INSERT INTO wordlist VALUES(null, 9, 'Butterfly');
INSERT INTO wordlist VALUES(null, 9, 'California condor');
INSERT INTO wordlist VALUES(null, 9, 'Camel');
INSERT INTO wordlist VALUES(null, 9, 'Caribou');
INSERT INTO wordlist VALUES(null, 9, 'Cat');
INSERT INTO wordlist VALUES(null, 9, 'Cat fish');
INSERT INTO wordlist VALUES(null, 9, 'Catipillar');
INSERT INTO wordlist VALUES(null, 9, 'Cheetah');
INSERT INTO wordlist VALUES(null, 9, 'Chia pet');
INSERT INTO wordlist VALUES(null, 9, 'Chimpanzee');
INSERT INTO wordlist VALUES(null, 9, 'Cobra');
INSERT INTO wordlist VALUES(null, 9, 'Cockatoo');
INSERT INTO wordlist VALUES(null, 9, 'Cockroach');
INSERT INTO wordlist VALUES(null, 9, 'Cougar');
INSERT INTO wordlist VALUES(null, 9, 'Coyote');
INSERT INTO wordlist VALUES(null, 9, 'Crab');
INSERT INTO wordlist VALUES(null, 9, 'Crocodile');
INSERT INTO wordlist VALUES(null, 9, 'Crow');
INSERT INTO wordlist VALUES(null, 9, 'Deer');
INSERT INTO wordlist VALUES(null, 9, 'Dinosaur');
INSERT INTO wordlist VALUES(null, 9, 'Dog');
INSERT INTO wordlist VALUES(null, 9, 'Dolphin');
INSERT INTO wordlist VALUES(null, 9, 'Donkey');
INSERT INTO wordlist VALUES(null, 9, 'Dove');
INSERT INTO wordlist VALUES(null, 9, 'Duck');
INSERT INTO wordlist VALUES(null, 9, 'Dugong');
INSERT INTO wordlist VALUES(null, 9, 'Eagle');
INSERT INTO wordlist VALUES(null, 9, 'Elephant');
INSERT INTO wordlist VALUES(null, 9, 'Elephant seal');
INSERT INTO wordlist VALUES(null, 9, 'Falcon');
INSERT INTO wordlist VALUES(null, 9, 'Ferret');
INSERT INTO wordlist VALUES(null, 9, 'Fish');
INSERT INTO wordlist VALUES(null, 9, 'Flamingo');
INSERT INTO wordlist VALUES(null, 9, 'Fox');
INSERT INTO wordlist VALUES(null, 9, 'Frog');
INSERT INTO wordlist VALUES(null, 9, 'Gazekke');
INSERT INTO wordlist VALUES(null, 9, 'Gerbuk');
INSERT INTO wordlist VALUES(null, 9, 'Giraffe');
INSERT INTO wordlist VALUES(null, 9, 'Goat');
INSERT INTO wordlist VALUES(null, 9, 'Goose');
INSERT INTO wordlist VALUES(null, 9, 'Gorilla');
INSERT INTO wordlist VALUES(null, 9, 'Guinea pig');
INSERT INTO wordlist VALUES(null, 9, 'Hamster');
INSERT INTO wordlist VALUES(null, 9, 'Hawk');
INSERT INTO wordlist VALUES(null, 9, 'Hippopotamus');
INSERT INTO wordlist VALUES(null, 9, 'Hornet');
INSERT INTO wordlist VALUES(null, 9, 'Horse');
INSERT INTO wordlist VALUES(null, 9, 'Howler monkey');
INSERT INTO wordlist VALUES(null, 9, 'Humming bird');
INSERT INTO wordlist VALUES(null, 9, 'Hummingbird');
INSERT INTO wordlist VALUES(null, 9, 'Jackal');
INSERT INTO wordlist VALUES(null, 9, 'Jaguar');
INSERT INTO wordlist VALUES(null, 9, 'Jellyfish');
INSERT INTO wordlist VALUES(null, 9, 'Kangaroo rat');
INSERT INTO wordlist VALUES(null, 9, 'Killer whale');
INSERT INTO wordlist VALUES(null, 9, 'King cobra snake');
INSERT INTO wordlist VALUES(null, 9, 'Kiwi bird');
INSERT INTO wordlist VALUES(null, 9, 'Koala');
INSERT INTO wordlist VALUES(null, 9, 'Lion');
INSERT INTO wordlist VALUES(null, 9, 'Llama');
INSERT INTO wordlist VALUES(null, 9, 'Lobster');
INSERT INTO wordlist VALUES(null, 9, 'Macaw');
INSERT INTO wordlist VALUES(null, 9, 'Manatee');
INSERT INTO wordlist VALUES(null, 9, 'Manta ray');
INSERT INTO wordlist VALUES(null, 9, 'Marmoset');
INSERT INTO wordlist VALUES(null, 9, 'Mink');
INSERT INTO wordlist VALUES(null, 9, 'Mole');
INSERT INTO wordlist VALUES(null, 9, 'Monkey');
INSERT INTO wordlist VALUES(null, 9, 'Moose');
INSERT INTO wordlist VALUES(null, 9, 'Moray eel');
INSERT INTO wordlist VALUES(null, 9, 'Mouse');
INSERT INTO wordlist VALUES(null, 9, 'Narwhal');
INSERT INTO wordlist VALUES(null, 9, 'Neanderthal');
INSERT INTO wordlist VALUES(null, 9, 'Newt');
INSERT INTO wordlist VALUES(null, 9, 'Ocelot');
INSERT INTO wordlist VALUES(null, 9, 'Orangutan');
INSERT INTO wordlist VALUES(null, 9, 'Orca');
INSERT INTO wordlist VALUES(null, 9, 'Ostrich');
INSERT INTO wordlist VALUES(null, 9, 'Otter');
INSERT INTO wordlist VALUES(null, 9, 'Owl');
INSERT INTO wordlist VALUES(null, 9, 'Ox');
INSERT INTO wordlist VALUES(null, 9, 'Panda');
INSERT INTO wordlist VALUES(null, 9, 'Pandas!');
INSERT INTO wordlist VALUES(null, 9, 'Panther');
INSERT INTO wordlist VALUES(null, 9, 'Parrot');
INSERT INTO wordlist VALUES(null, 9, 'Penguin');
INSERT INTO wordlist VALUES(null, 9, 'Pheasant');
INSERT INTO wordlist VALUES(null, 9, 'Pig');
INSERT INTO wordlist VALUES(null, 9, 'Pigeon');
INSERT INTO wordlist VALUES(null, 9, 'Prairie dog');
INSERT INTO wordlist VALUES(null, 9, 'Rabbit');
INSERT INTO wordlist VALUES(null, 9, 'Raccoon');
INSERT INTO wordlist VALUES(null, 9, 'Ram');
INSERT INTO wordlist VALUES(null, 9, 'Rat');
INSERT INTO wordlist VALUES(null, 9, 'Raven');
INSERT INTO wordlist VALUES(null, 9, 'Rhino');
INSERT INTO wordlist VALUES(null, 9, 'Rhinoceros');
INSERT INTO wordlist VALUES(null, 9, 'Rooster');
INSERT INTO wordlist VALUES(null, 9, 'Sea lion');
INSERT INTO wordlist VALUES(null, 9, 'Sea urchin');
INSERT INTO wordlist VALUES(null, 9, 'Shark');
INSERT INTO wordlist VALUES(null, 9, 'Sheep');
INSERT INTO wordlist VALUES(null, 9, 'Skunk');
INSERT INTO wordlist VALUES(null, 9, 'Snake');
INSERT INTO wordlist VALUES(null, 9, 'Sparrow');
INSERT INTO wordlist VALUES(null, 9, 'Sugar glider');
INSERT INTO wordlist VALUES(null, 9, 'Swan');
INSERT INTO wordlist VALUES(null, 9, 'Tiger');
INSERT INTO wordlist VALUES(null, 9, 'Toad');
INSERT INTO wordlist VALUES(null, 9, 'Wasp');
INSERT INTO wordlist VALUES(null, 9, 'Whale');
INSERT INTO wordlist VALUES(null, 9, 'Wolf');
INSERT INTO wordlist VALUES(null, 9, 'Wolverine');
INSERT INTO wordlist VALUES(null, 9, 'Wooly mammoth');
INSERT INTO wordlist VALUES(null, 9, 'Worm');
INSERT INTO wordlist VALUES(null, 9, 'Yak');
INSERT INTO wordlist VALUES(null, 9, 'Zebra');